# Application Name
spring.application.name=AgriLinkerBackend

# MongoDB connection
spring.data.mongodb.uri=mongodb+srv://anneperera008_db_user:h8BB3sxdeyRzoDdo@agrilinkerdb.cw2gele.mongodb.net/agrilinkerdb?retryWrites=true&w=majority&ssl=true

# Server port
server.port=8081

# JWT configuration
jwt.secret=Zx3!5yKp8Qw7#R4mU2tBvC6fN9gH1jL0
jwt.expiration=86400000

# File upload configuration
# Path where uploaded images/files will be stored
file.upload-dir=uploads

# Maximum file size (optional, adjust as needed)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
