spring.application.name=AgriLinkerBackend

# Complete connection string with database name
spring.data.mongodb.uri=mongodb+srv://anneperera008_db_user:h8BB3sxdeyRzoDdo@agrilinkerdb.cw2gele.mongodb.net/agrilinkerdb?retryWrites=true&w=majority&ssl=true

server.port=8081